/*************************************
* Intro to Prgramming 
**************************************
* Anu Kalnad
* 8/21/2020
* CMC 225 003
**************************************/

public class Hello {

	public static void main(String[] args) {
	
	System.out.println("Anu Kalnad>");
	System.out.println("Lab 01");
	System.out.println("Coding");
	System.out.println("8/21/2020");
	System.out.println("CMC 225 003");
	System.out.println();
	}
}